# Generated by Django 2.2.28 on 2023-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0002_auto_20191205_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='valid_from',
            field=models.DateField(verbose_name='Действителен с'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valid_to',
            field=models.DateField(verbose_name='Действителен до'),
        ),
    ]
