# Generated by Django 2.2.28 on 2023-02-07 20:20

from django.db import migrations, models
import lenivastore.models


class Migration(migrations.Migration):

    dependencies = [
        ('lenivastore', '0003_auto_20191205_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('link', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to=lenivastore.models.get_upload_path, verbose_name='Изображение_новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
