# Generated by Django 2.2.28 on 2023-02-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenivastore', '0004_add_news_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=300, unique=True, verbose_name='Ссылка'),
        ),
    ]
