# Generated by Django 2.2.28 on 2023-02-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenivastore', '0005_changed_type_link_in_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение_новости'),
        ),
    ]
