# Generated by Django 2.2.28 on 2023-03-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenivastore', '0007_add_subcategory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='lenivastore.Subcategory', verbose_name='Подкатегория'),
        ),
    ]
