# Generated by Django 2.2.28 on 2023-03-23 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenivastore', '0009_add_rating_and_stars_fields_in_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Рейтинг от 0.0 до 5.0')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Кол-во звезд от 0 до 5')], verbose_name='Кол-во звезд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='lenivastore.Subcategory', verbose_name='Подкатегория'),
        ),
    ]
