# Generated by Django 2.2.28 on 2023-03-23 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenivastore', '0010_change_rating_and_stars_fields_in_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Рейтинг/кол-во звезд от 0 до 5'), django.core.validators.MinValueValidator(0, 'Рейтинг/кол-во звезд от 0 до 5')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5, 'Рейтинг/кол-во звезд от 0 до 5')], verbose_name='Кол-во звезд'),
        ),
    ]
