# Generated by Django 2.2.28 on 2023-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_set_blank_true_in_some_fields_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_paid',
            field=models.BooleanField(default=False, verbose_name='Онлайн оплата'),
        ),
    ]
