# Generated by Django 2.2.28 on 2023-04-05 09:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_callback_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
