# Generated by Django 2.2.28 on 2023-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_deleted_filelds_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0, verbose_name='Итоговая стоимость заказа'),
        ),
    ]
